version: '3'
services:
  server:
    build: 
      context: .
    links:
      - db
    volumes:
      - "${PWD}:/service"
    ports:
      - "8000:8000"
    networks:
      - sanic-network
    environment:
      POSTGRES_SERVICE_DB_NAME: postgres
      POSTGRES_SERVICE_USER: postgres
      POSTGRES_SERVICE_HOST: db
      POSTGRES_SERVICE_PORT: 5432

      #command: python -m sanic server.app --host=0.0.0.0 --port=8000 --workers=4
    depends_on:
      - "db"
    command: ["python", "-m", "server"]
    #command: ["python", "-m", 'sanic', "service.server.app", "--workers=4", "--port=8000", "--host=0.0.0.0"]

  db:
    image: "postgres:9.6"
    networks:
        - sanic-network

networks:
  sanic-network:
    driver: bridge

